apiVersion: batch/v1
kind: CronJob
metadata:
  name: log-generator
  namespace: kafka
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: kcat
              image: edenhill/kcat:1.7.1
              command: ["/bin/sh","-c"]
              args:
                - |
                  for i in $(seq 1 50); do
                    echo "{\"level\":\"INFO\",\"msg\":\"Log event from app #$i\"}" \
                    | kcat -P -b kafka-cluster-kafka-bootstrap.kafka:9092 -t logs-topic -k app;
                  done
