apiVersion: batch/v1
kind: CronJob
metadata:
  name: log-generator
  namespace: kafka
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: logger
              image: busybox
              command: ["/bin/sh", "-c"]
              args:
                - 'echo ''{"level":"INFO","msg":"Log event from app"}'' | nc kafka-cluster-kafka-bootstrap.kafka 9092'
          restartPolicy: OnFailure
