apiVersion: batch/v1
kind: CronJob
metadata:
  name: log-generator
  namespace: kafka
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: kafka-producer
              image: bitnami/kafka:latest
              command: ["/bin/bash", "-c"]
              args:
                - |
                  for i in {1..10}; do
                    echo "{\"level\": \"INFO\", \"message\": \"Log entry $i\", \"timestamp\": \"$(date --utc +%FT%TZ)\"}" \
                      | kafka-console-producer.sh --broker-list my-cluster-kafka-bootstrap.kafka:9092 --topic logs-topic;
                    sleep 1;
                  done
          restartPolicy: OnFailure
