apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: logging
data:
  logstash.conf: |
    input {
      kafka {
        topics => ["logs-topic"]
        bootstrap_servers => "kafka-cluster-kafka-bootstrap.kafka:9092"
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch-master.logging.svc:9200"]
        index => "logs-%{+YYYY.MM.dd}"
      }
    }
